apiVersion: apps/v1 
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 2 
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: docker.io/yourhubusername/auth:1.0 #Change yourhubusername
        ports:
        - containerPort: 8080
        env:
        - name: OSDU_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: baseurl
              key: OSDU_CLIENT_ID
        - name: OSDU_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: baseurl
              key: OSDU_CLIENT_SECRET
        - name: OSDU_AUTH_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: baseurl
              key: OSDU_AUTH_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
  labels:
    app: auth
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: auth
  type: ClusterIP
